# Generated by Django 3.1 on 2020-08-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_todolist_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='desc',
        ),
    ]
