# Generated by Django 3.1 on 2020-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_todolist_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='desc',
            field=models.TextField(default='Description goes here...'),
            preserve_default=False,
        ),
    ]
